"""
Diagnostic Error Analysis & Failure Attribution Script for Amazon ML Challenge 2026.
Per Implementation Plan Section 11:
Categorizes errors into:
1. PIPELINE_BUG: predicted outside candidates
2. BLOCKING_MISS: true match never generated by blocking
3. CLASSIFIER_MISS: true match was a candidate but scored below threshold
4. FALSE_POSITIVE: candidate scored above threshold but is not a true match
"""

import os
import argparse
from typing import Dict, List, Set
from collections import defaultdict
from evaluate import compute_entity_f05

def run_error_analysis(
    gt_map: Dict[str, Set[str]],
    cand_map: Dict[str, List[str]],
    pred_map: Dict[str, List[str]],
    out_dir: str = "error_analysis_out"
):
    os.makedirs(out_dir, exist_ok=True)
    
    total_entities = len(gt_map)
    blocking_misses = []
    classifier_misses = []
    false_positives = []
    pipeline_bugs = []
    entity_scores = []
    
    for s1_id, true_matches in gt_map.items():
        candidates = set(cand_map.get(s1_id, []))
        predictions = set(pred_map.get(s1_id, []))
        
        f05 = compute_entity_f05(predictions, true_matches)
        entity_scores.append((s1_id, f05, len(true_matches), len(predictions)))
        
        # Check false positives
        for p in predictions:
            if p not in true_matches:
                if p not in candidates:
                    pipeline_bugs.append((s1_id, p, "predicted_outside_candidates"))
                else:
                    false_positives.append((s1_id, p))
                    
        # Check false negatives
        for t in true_matches:
            if t not in predictions:
                if t not in candidates:
                    blocking_misses.append((s1_id, t))
                else:
                    classifier_misses.append((s1_id, t))
                    
    # Sort worst entities first
    entity_scores.sort(key=lambda x: x[1])
    
    # Write summary
    summary_path = os.path.join(out_dir, "summary.txt")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write("=== ERROR ANALYSIS & ATTRIBUTION SUMMARY ===\n")
        f.write(f"Total S1 Entities Evaluated: {total_entities:,}\n")
        f.write(f"Blocking Misses (Recall Ceiling Gaps)  : {len(blocking_misses):,}\n")
        f.write(f"Classifier Misses (Under-threshold)   : {len(classifier_misses):,}\n")
        f.write(f"False Positives (Classifier Merges)   : {len(false_positives):,}\n")
        f.write(f"Pipeline Bugs (Outside Candidates)    : {len(pipeline_bugs):,}\n\n")
        
        total_misses = len(blocking_misses) + len(classifier_misses)
        if total_misses > 0:
            b_pct = (len(blocking_misses) / total_misses) * 100
            c_pct = (len(classifier_misses) / total_misses) * 100
            f.write(f"Missed Match Attribution: {b_pct:.1f}% Blocking vs {c_pct:.1f}% Classifier\n")
            
    print(f"Error analysis written to {summary_path}")
    print(f"  Blocking Misses    : {len(blocking_misses):,}")
    print(f"  Classifier Misses  : {len(classifier_misses):,}")
    print(f"  False Positives    : {len(false_positives):,}")
    print(f"  Pipeline Bugs      : {len(pipeline_bugs):,}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Error Analysis Tool")
    parser.add_argument("--out-dir", default="error_analysis_out")
    args = parser.parse_args()
    print("Run error analysis by importing run_error_analysis.")
